# Name is optional and if present must be used
# in the url path for badges
name: Test workflow on push

# on: # [push, pull_request]
#   pull_request:
#     branches: [main]
#     types: [opened]
#   push:
#     types: [opened]

on: [push, pull_request]
  # pull_request:
  #   types: [assigned, opened, synchronize, reopened]
  # push:
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Only push to repo
      - name: Run only on push
        if: ${{ github.event_name == 'push' && github.ref != 'refs/heads/master'}}
        run: |
          echo "Run only Push"

      # Commits to master
      - name: Run on send commits to master
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        run: |
          echo "Run only PR master"
