# Name is optional and if present must be used
# in the url path for badges
name: Test workflow on push

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "RODANDO O CI"